/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceIntelligenceRouteImport } from './routes/workforce-intelligence'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TalentIntelligenceRouteImport } from './routes/talent-intelligence'
import { Route as SlackRouteImport } from './routes/slack'
import { Route as SkillsIntelligenceRouteImport } from './routes/skills-intelligence'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as RfpMatcherRouteImport } from './routes/rfp-matcher'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PromotionReadinessRouteImport } from './routes/promotion-readiness'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as JiraRouteImport } from './routes/jira'
import { Route as HiringPipelineRouteImport } from './routes/hiring-pipeline'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ExcelUploadRouteImport } from './routes/excel-upload'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ClickupRouteImport } from './routes/clickup'
import { Route as CandidateSearchRouteImport } from './routes/candidate-search'
import { Route as BurnoutRiskRouteImport } from './routes/burnout-risk'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiIntelligenceRouteImport } from './routes/ai-intelligence'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiWorkspaceIndexRouteImport } from './routes/ai-workspace.index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as ApiTalentChatRouteImport } from './routes/api/talent-chat'
import { Route as AiWorkspaceJobMatcherRouteImport } from './routes/ai-workspace.job-matcher'
import { Route as AiWorkspaceCompareRouteImport } from './routes/ai-workspace.compare'
import { Route as AiWorkspaceChatThreadIdRouteImport } from './routes/ai-workspace.chat.$threadId'
import { Route as ApiPublicJiraCallbackRouteImport } from './routes/api/public/jira/callback'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github/callback'
import { Route as ApiPublicClickupCallbackRouteImport } from './routes/api/public/clickup/callback'

const WorkforceIntelligenceRoute = WorkforceIntelligenceRouteImport.update({
  id: '/workforce-intelligence',
  path: '/workforce-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIntelligenceRoute = TalentIntelligenceRouteImport.update({
  id: '/talent-intelligence',
  path: '/talent-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackRoute = SlackRouteImport.update({
  id: '/slack',
  path: '/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIntelligenceRoute = SkillsIntelligenceRouteImport.update({
  id: '/skills-intelligence',
  path: '/skills-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpMatcherRoute = RfpMatcherRouteImport.update({
  id: '/rfp-matcher',
  path: '/rfp-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionReadinessRoute = PromotionReadinessRouteImport.update({
  id: '/promotion-readiness',
  path: '/promotion-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const JiraRoute = JiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringPipelineRoute = HiringPipelineRouteImport.update({
  id: '/hiring-pipeline',
  path: '/hiring-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelUploadRoute = ExcelUploadRouteImport.update({
  id: '/excel-upload',
  path: '/excel-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClickupRoute = ClickupRouteImport.update({
  id: '/clickup',
  path: '/clickup',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSearchRoute = CandidateSearchRouteImport.update({
  id: '/candidate-search',
  path: '/candidate-search',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnoutRiskRoute = BurnoutRiskRouteImport.update({
  id: '/burnout-risk',
  path: '/burnout-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntelligenceRoute = AiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceIndexRoute = AiWorkspaceIndexRouteImport.update({
  id: '/ai-workspace/',
  path: '/ai-workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DepartmentsRoute,
} as any)
const ApiTalentChatRoute = ApiTalentChatRouteImport.update({
  id: '/api/talent-chat',
  path: '/api/talent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceJobMatcherRoute = AiWorkspaceJobMatcherRouteImport.update({
  id: '/ai-workspace/job-matcher',
  path: '/ai-workspace/job-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceCompareRoute = AiWorkspaceCompareRouteImport.update({
  id: '/ai-workspace/compare',
  path: '/ai-workspace/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceChatThreadIdRoute = AiWorkspaceChatThreadIdRouteImport.update({
  id: '/ai-workspace/chat/$threadId',
  path: '/ai-workspace/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJiraCallbackRoute = ApiPublicJiraCallbackRouteImport.update({
  id: '/api/public/jira/callback',
  path: '/api/public/jira/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github/callback',
  path: '/api/public/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClickupCallbackRoute =
  ApiPublicClickupCallbackRouteImport.update({
    id: '/api/public/clickup/callback',
    path: '/api/public/clickup/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/burnout-risk': typeof BurnoutRiskRoute
  '/candidate-search': typeof CandidateSearchRoute
  '/clickup': typeof ClickupRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/excel-upload': typeof ExcelUploadRoute
  '/github': typeof GithubRoute
  '/hiring-pipeline': typeof HiringPipelineRoute
  '/jira': typeof JiraRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRoute
  '/promotion-readiness': typeof PromotionReadinessRoute
  '/reports': typeof ReportsRoute
  '/rfp-matcher': typeof RfpMatcherRoute
  '/server-error': typeof ServerErrorRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills-intelligence': typeof SkillsIntelligenceRoute
  '/slack': typeof SlackRoute
  '/talent-intelligence': typeof TalentIntelligenceRoute
  '/teams': typeof TeamsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workforce-intelligence': typeof WorkforceIntelligenceRoute
  '/ai-workspace/compare': typeof AiWorkspaceCompareRoute
  '/ai-workspace/job-matcher': typeof AiWorkspaceJobMatcherRoute
  '/api/talent-chat': typeof ApiTalentChatRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/ai-workspace/': typeof AiWorkspaceIndexRoute
  '/ai-workspace/chat/$threadId': typeof AiWorkspaceChatThreadIdRoute
  '/api/public/clickup/callback': typeof ApiPublicClickupCallbackRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/jira/callback': typeof ApiPublicJiraCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/burnout-risk': typeof BurnoutRiskRoute
  '/candidate-search': typeof CandidateSearchRoute
  '/clickup': typeof ClickupRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/excel-upload': typeof ExcelUploadRoute
  '/github': typeof GithubRoute
  '/hiring-pipeline': typeof HiringPipelineRoute
  '/jira': typeof JiraRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRoute
  '/promotion-readiness': typeof PromotionReadinessRoute
  '/reports': typeof ReportsRoute
  '/rfp-matcher': typeof RfpMatcherRoute
  '/server-error': typeof ServerErrorRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills-intelligence': typeof SkillsIntelligenceRoute
  '/slack': typeof SlackRoute
  '/talent-intelligence': typeof TalentIntelligenceRoute
  '/teams': typeof TeamsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workforce-intelligence': typeof WorkforceIntelligenceRoute
  '/ai-workspace/compare': typeof AiWorkspaceCompareRoute
  '/ai-workspace/job-matcher': typeof AiWorkspaceJobMatcherRoute
  '/api/talent-chat': typeof ApiTalentChatRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/ai-workspace': typeof AiWorkspaceIndexRoute
  '/ai-workspace/chat/$threadId': typeof AiWorkspaceChatThreadIdRoute
  '/api/public/clickup/callback': typeof ApiPublicClickupCallbackRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/jira/callback': typeof ApiPublicJiraCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/ai-intelligence': typeof AiIntelligenceRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/burnout-risk': typeof BurnoutRiskRoute
  '/candidate-search': typeof CandidateSearchRoute
  '/clickup': typeof ClickupRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/excel-upload': typeof ExcelUploadRoute
  '/github': typeof GithubRoute
  '/hiring-pipeline': typeof HiringPipelineRoute
  '/jira': typeof JiraRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/projects': typeof ProjectsRoute
  '/promotion-readiness': typeof PromotionReadinessRoute
  '/reports': typeof ReportsRoute
  '/rfp-matcher': typeof RfpMatcherRoute
  '/server-error': typeof ServerErrorRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills-intelligence': typeof SkillsIntelligenceRoute
  '/slack': typeof SlackRoute
  '/talent-intelligence': typeof TalentIntelligenceRoute
  '/teams': typeof TeamsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workforce-intelligence': typeof WorkforceIntelligenceRoute
  '/ai-workspace/compare': typeof AiWorkspaceCompareRoute
  '/ai-workspace/job-matcher': typeof AiWorkspaceJobMatcherRoute
  '/api/talent-chat': typeof ApiTalentChatRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/ai-workspace/': typeof AiWorkspaceIndexRoute
  '/ai-workspace/chat/$threadId': typeof AiWorkspaceChatThreadIdRoute
  '/api/public/clickup/callback': typeof ApiPublicClickupCallbackRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/jira/callback': typeof ApiPublicJiraCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/ai-intelligence'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/burnout-risk'
    | '/candidate-search'
    | '/clickup'
    | '/departments'
    | '/employees'
    | '/excel-upload'
    | '/github'
    | '/hiring-pipeline'
    | '/jira'
    | '/maintenance'
    | '/notifications'
    | '/onboarding'
    | '/permissions'
    | '/projects'
    | '/promotion-readiness'
    | '/reports'
    | '/rfp-matcher'
    | '/server-error'
    | '/settings'
    | '/sitemap.xml'
    | '/skills-intelligence'
    | '/slack'
    | '/talent-intelligence'
    | '/teams'
    | '/unauthorized'
    | '/workforce-intelligence'
    | '/ai-workspace/compare'
    | '/ai-workspace/job-matcher'
    | '/api/talent-chat'
    | '/departments/$id'
    | '/employees/$id'
    | '/ai-workspace/'
    | '/ai-workspace/chat/$threadId'
    | '/api/public/clickup/callback'
    | '/api/public/github/callback'
    | '/api/public/jira/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/ai-intelligence'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/burnout-risk'
    | '/candidate-search'
    | '/clickup'
    | '/departments'
    | '/employees'
    | '/excel-upload'
    | '/github'
    | '/hiring-pipeline'
    | '/jira'
    | '/maintenance'
    | '/notifications'
    | '/onboarding'
    | '/permissions'
    | '/projects'
    | '/promotion-readiness'
    | '/reports'
    | '/rfp-matcher'
    | '/server-error'
    | '/settings'
    | '/sitemap.xml'
    | '/skills-intelligence'
    | '/slack'
    | '/talent-intelligence'
    | '/teams'
    | '/unauthorized'
    | '/workforce-intelligence'
    | '/ai-workspace/compare'
    | '/ai-workspace/job-matcher'
    | '/api/talent-chat'
    | '/departments/$id'
    | '/employees/$id'
    | '/ai-workspace'
    | '/ai-workspace/chat/$threadId'
    | '/api/public/clickup/callback'
    | '/api/public/github/callback'
    | '/api/public/jira/callback'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/ai-intelligence'
    | '/analytics'
    | '/auth'
    | '/billing'
    | '/burnout-risk'
    | '/candidate-search'
    | '/clickup'
    | '/departments'
    | '/employees'
    | '/excel-upload'
    | '/github'
    | '/hiring-pipeline'
    | '/jira'
    | '/maintenance'
    | '/notifications'
    | '/onboarding'
    | '/permissions'
    | '/projects'
    | '/promotion-readiness'
    | '/reports'
    | '/rfp-matcher'
    | '/server-error'
    | '/settings'
    | '/sitemap.xml'
    | '/skills-intelligence'
    | '/slack'
    | '/talent-intelligence'
    | '/teams'
    | '/unauthorized'
    | '/workforce-intelligence'
    | '/ai-workspace/compare'
    | '/ai-workspace/job-matcher'
    | '/api/talent-chat'
    | '/departments/$id'
    | '/employees/$id'
    | '/ai-workspace/'
    | '/ai-workspace/chat/$threadId'
    | '/api/public/clickup/callback'
    | '/api/public/github/callback'
    | '/api/public/jira/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AiIntelligenceRoute: typeof AiIntelligenceRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  BurnoutRiskRoute: typeof BurnoutRiskRoute
  CandidateSearchRoute: typeof CandidateSearchRoute
  ClickupRoute: typeof ClickupRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  EmployeesRoute: typeof EmployeesRouteWithChildren
  ExcelUploadRoute: typeof ExcelUploadRoute
  GithubRoute: typeof GithubRoute
  HiringPipelineRoute: typeof HiringPipelineRoute
  JiraRoute: typeof JiraRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PermissionsRoute: typeof PermissionsRoute
  ProjectsRoute: typeof ProjectsRoute
  PromotionReadinessRoute: typeof PromotionReadinessRoute
  ReportsRoute: typeof ReportsRoute
  RfpMatcherRoute: typeof RfpMatcherRoute
  ServerErrorRoute: typeof ServerErrorRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsIntelligenceRoute: typeof SkillsIntelligenceRoute
  SlackRoute: typeof SlackRoute
  TalentIntelligenceRoute: typeof TalentIntelligenceRoute
  TeamsRoute: typeof TeamsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WorkforceIntelligenceRoute: typeof WorkforceIntelligenceRoute
  AiWorkspaceCompareRoute: typeof AiWorkspaceCompareRoute
  AiWorkspaceJobMatcherRoute: typeof AiWorkspaceJobMatcherRoute
  ApiTalentChatRoute: typeof ApiTalentChatRoute
  AiWorkspaceIndexRoute: typeof AiWorkspaceIndexRoute
  AiWorkspaceChatThreadIdRoute: typeof AiWorkspaceChatThreadIdRoute
  ApiPublicClickupCallbackRoute: typeof ApiPublicClickupCallbackRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
  ApiPublicJiraCallbackRoute: typeof ApiPublicJiraCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce-intelligence': {
      id: '/workforce-intelligence'
      path: '/workforce-intelligence'
      fullPath: '/workforce-intelligence'
      preLoaderRoute: typeof WorkforceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-intelligence': {
      id: '/talent-intelligence'
      path: '/talent-intelligence'
      fullPath: '/talent-intelligence'
      preLoaderRoute: typeof TalentIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack': {
      id: '/slack'
      path: '/slack'
      fullPath: '/slack'
      preLoaderRoute: typeof SlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-intelligence': {
      id: '/skills-intelligence'
      path: '/skills-intelligence'
      fullPath: '/skills-intelligence'
      preLoaderRoute: typeof SkillsIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfp-matcher': {
      id: '/rfp-matcher'
      path: '/rfp-matcher'
      fullPath: '/rfp-matcher'
      preLoaderRoute: typeof RfpMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion-readiness': {
      id: '/promotion-readiness'
      path: '/promotion-readiness'
      fullPath: '/promotion-readiness'
      preLoaderRoute: typeof PromotionReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira': {
      id: '/jira'
      path: '/jira'
      fullPath: '/jira'
      preLoaderRoute: typeof JiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring-pipeline': {
      id: '/hiring-pipeline'
      path: '/hiring-pipeline'
      fullPath: '/hiring-pipeline'
      preLoaderRoute: typeof HiringPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel-upload': {
      id: '/excel-upload'
      path: '/excel-upload'
      fullPath: '/excel-upload'
      preLoaderRoute: typeof ExcelUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clickup': {
      id: '/clickup'
      path: '/clickup'
      fullPath: '/clickup'
      preLoaderRoute: typeof ClickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-search': {
      id: '/candidate-search'
      path: '/candidate-search'
      fullPath: '/candidate-search'
      preLoaderRoute: typeof CandidateSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burnout-risk': {
      id: '/burnout-risk'
      path: '/burnout-risk'
      fullPath: '/burnout-risk'
      preLoaderRoute: typeof BurnoutRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-intelligence': {
      id: '/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/ai-intelligence'
      preLoaderRoute: typeof AiIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace/': {
      id: '/ai-workspace/'
      path: '/ai-workspace'
      fullPath: '/ai-workspace/'
      preLoaderRoute: typeof AiWorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/api/talent-chat': {
      id: '/api/talent-chat'
      path: '/api/talent-chat'
      fullPath: '/api/talent-chat'
      preLoaderRoute: typeof ApiTalentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace/job-matcher': {
      id: '/ai-workspace/job-matcher'
      path: '/ai-workspace/job-matcher'
      fullPath: '/ai-workspace/job-matcher'
      preLoaderRoute: typeof AiWorkspaceJobMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace/compare': {
      id: '/ai-workspace/compare'
      path: '/ai-workspace/compare'
      fullPath: '/ai-workspace/compare'
      preLoaderRoute: typeof AiWorkspaceCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace/chat/$threadId': {
      id: '/ai-workspace/chat/$threadId'
      path: '/ai-workspace/chat/$threadId'
      fullPath: '/ai-workspace/chat/$threadId'
      preLoaderRoute: typeof AiWorkspaceChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jira/callback': {
      id: '/api/public/jira/callback'
      path: '/api/public/jira/callback'
      fullPath: '/api/public/jira/callback'
      preLoaderRoute: typeof ApiPublicJiraCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/callback': {
      id: '/api/public/github/callback'
      path: '/api/public/github/callback'
      fullPath: '/api/public/github/callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clickup/callback': {
      id: '/api/public/clickup/callback'
      path: '/api/public/clickup/callback'
      fullPath: '/api/public/clickup/callback'
      preLoaderRoute: typeof ApiPublicClickupCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DepartmentsRouteChildren {
  DepartmentsIdRoute: typeof DepartmentsIdRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsIdRoute: DepartmentsIdRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AiIntelligenceRoute: AiIntelligenceRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  BurnoutRiskRoute: BurnoutRiskRoute,
  CandidateSearchRoute: CandidateSearchRoute,
  ClickupRoute: ClickupRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  EmployeesRoute: EmployeesRouteWithChildren,
  ExcelUploadRoute: ExcelUploadRoute,
  GithubRoute: GithubRoute,
  HiringPipelineRoute: HiringPipelineRoute,
  JiraRoute: JiraRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PermissionsRoute: PermissionsRoute,
  ProjectsRoute: ProjectsRoute,
  PromotionReadinessRoute: PromotionReadinessRoute,
  ReportsRoute: ReportsRoute,
  RfpMatcherRoute: RfpMatcherRoute,
  ServerErrorRoute: ServerErrorRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsIntelligenceRoute: SkillsIntelligenceRoute,
  SlackRoute: SlackRoute,
  TalentIntelligenceRoute: TalentIntelligenceRoute,
  TeamsRoute: TeamsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WorkforceIntelligenceRoute: WorkforceIntelligenceRoute,
  AiWorkspaceCompareRoute: AiWorkspaceCompareRoute,
  AiWorkspaceJobMatcherRoute: AiWorkspaceJobMatcherRoute,
  ApiTalentChatRoute: ApiTalentChatRoute,
  AiWorkspaceIndexRoute: AiWorkspaceIndexRoute,
  AiWorkspaceChatThreadIdRoute: AiWorkspaceChatThreadIdRoute,
  ApiPublicClickupCallbackRoute: ApiPublicClickupCallbackRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
  ApiPublicJiraCallbackRoute: ApiPublicJiraCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
